### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Yuiiiiichi** [jacksonlevine/voxelland#1]
Hello,

The cargo workspace file reference a member that doesn't exist or isn't pushed, therefore the build cannot succeed.

https://github.com/jacksonlevine/voxelland/blob/f134f131d71012b98ca6ed5992c3f1f54b8f62b5/Cargo.toml#L6

Thank you

**Comment by jacksonlevine** [comment]
Hey, sorry about that I forgot to commit the corresponding Cargo.toml
changes to deleting that client. I will push the fix, feel free to just
delete the "test_client" entry though
